training:
  strategy: fsdp # can be changed to fsdp
  seed: 1337

  batch_size: 40
  num_workers: 10
  prefetch_factor: 2
  
  learning_rate: 2e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  adam_betas: [0.9, 0.999]

  warmup_steps: 2000
  max_steps: 100000
  validation_steps: 500
  log_interval: 10

  enable_tf32: True
  enable_amp: False

datasets:
  _target_: flava.definitions.TrainingDatasetsInfo
  selected:
  - image
  - vl
  - text
  image:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: imagenet-1k
        subset: default
  text:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: wikitext
        subset: wikitext-103-raw-v1
    datamodule_extra_kwargs:
      text_columns: ["text"]
  vl:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: red_caps
        subset: jellyfish
        rename_columns:
          - ["caption", "text"]
    val:
      - _target_: flava.definitions.HFDatasetInfo
        key: red_caps
        subset: jellyfish
        rename_columns:
          - ["caption", "text"]
        split_key_mapping:
          validation: train

model:
  image_num_hidden_layers: 32
  image_hidden_size: 1280
  image_intermediate_size: 5120
  image_num_attention_heads: 16

  text_num_hidden_layers: 32
  text_hidden_size: 1280
  text_intermediate_size: 5120 
  text_num_attention_heads: 16

  multimodal_num_hidden_layers: 24
  multimodal_hidden_size: 1280
  multimodal_intermediate_size: 5120
  multimodal_num_attention_heads: 16
