# Note that in original FLAVA paper, only Logistic Regression numbers were provided for image datasets.
_target_: flava.definitions.FLAVAArguments
training:
  _target_: flava.definitions.TrainingArguments
  lightning:
    max_steps: 33112
    gpus: 1
    progress_bar_refresh_rate: 50
    val_check_interval: 1000
    num_sanity_val_steps: 0
    strategy: ddp
  lightning_checkpoint:
    dirpath: "."
    filename: flava-{epoch:02d}-{step}
    save_last: true
    every_n_train_steps: 1000
    save_on_train_epoch_end: true
    verbose: true
    monitor: validation/accuracy/classification
    mode: max
  lightning_load_from_checkpoint: null
  seed: -1
  batch_size: 32
  num_workers: 4
  learning_rate: 1e-5
  adam_eps: 1e-6
  adam_weight_decay: 0.1
  adam_betas:
  - 0.9
  - 0.98
  warmup_steps: 1986


datasets:
  _target_: flava.definitions.TrainingDatasetsInfo
  selected:
  - text
  num_classes: 2
  text:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: glue
        subset: qnli
        rename_columns:
          - ["question", "sentence1"]
          - ["sentence", "sentence2"]
    datamodule_extra_kwargs:
      text_columns: ["sentence1", "sentence2"]
